### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Alicebjw** [qdin4048/CPL-OT#1]
Dear author, when I clone your code, The data set required for entity name embedding always shows "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. "Can you put a link back to the data set.Looking forward to your reply

**Comment by qdin4048** [comment]
Hi Alicebjw,

Sorry for the inconvenience, I have updated a link in the description for downloading the entire data folder, please have a try:)

**Comment by Alicebjw** [comment]
Thanks very much！I've got the data sets！At the same time, I would also like to ask if the pre-trained word embedding vector index numbers correspond to the entity id numbers in the data sets.

**Comment by qdin4048** [comment]
Yes, they do.
